//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CourierBackOfficeManagement.CorporateCourierEntry {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CorporateCourierEntryWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CorporateCourierEntryWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CorporateClientOrderEntryAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback CorporateClientOrderEntryUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CorporateClientOrderEntryGetByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchCorporateClientOrderEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPageDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCorporateClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback LocationNameGetByCorporateClientLocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CorporateClientOrderCancelByIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CorporateCourierEntryWebService() {
            this.Url = global::CourierBackOfficeManagement.Properties.Settings.Default.CourierBackOfficeManagement_CorporateCourierEntry_CorporateCourierEntryWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CorporateClientOrderEntryAddCompletedEventHandler CorporateClientOrderEntryAddCompleted;
        
        /// <remarks/>
        public event CorporateClientOrderEntryUpdateCompletedEventHandler CorporateClientOrderEntryUpdateCompleted;
        
        /// <remarks/>
        public event CorporateClientOrderEntryGetByIDCompletedEventHandler CorporateClientOrderEntryGetByIDCompleted;
        
        /// <remarks/>
        public event SearchCorporateClientOrderEntryCompletedEventHandler SearchCorporateClientOrderEntryCompleted;
        
        /// <remarks/>
        public event GetPageDataCompletedEventHandler GetPageDataCompleted;
        
        /// <remarks/>
        public event GetAllCorporateClientCompletedEventHandler GetAllCorporateClientCompleted;
        
        /// <remarks/>
        public event LocationNameGetByCorporateClientLocationCompletedEventHandler LocationNameGetByCorporateClientLocationCompleted;
        
        /// <remarks/>
        public event CorporateClientOrderCancelByIDCompletedEventHandler CorporateClientOrderCancelByIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CorporateClientOrderEntryAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CorporateClientOrderEntryAdd(CorporateClientOrderInfo objInfo, string token) {
            this.Invoke("CorporateClientOrderEntryAdd", new object[] {
                        objInfo,
                        token});
        }
        
        /// <remarks/>
        public void CorporateClientOrderEntryAddAsync(CorporateClientOrderInfo objInfo, string token) {
            this.CorporateClientOrderEntryAddAsync(objInfo, token, null);
        }
        
        /// <remarks/>
        public void CorporateClientOrderEntryAddAsync(CorporateClientOrderInfo objInfo, string token, object userState) {
            if ((this.CorporateClientOrderEntryAddOperationCompleted == null)) {
                this.CorporateClientOrderEntryAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCorporateClientOrderEntryAddOperationCompleted);
            }
            this.InvokeAsync("CorporateClientOrderEntryAdd", new object[] {
                        objInfo,
                        token}, this.CorporateClientOrderEntryAddOperationCompleted, userState);
        }
        
        private void OnCorporateClientOrderEntryAddOperationCompleted(object arg) {
            if ((this.CorporateClientOrderEntryAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CorporateClientOrderEntryAddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CorporateClientOrderEntryUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CorporateClientOrderEntryUpdate(CorporateClientOrderInfo objInfo, string token) {
            this.Invoke("CorporateClientOrderEntryUpdate", new object[] {
                        objInfo,
                        token});
        }
        
        /// <remarks/>
        public void CorporateClientOrderEntryUpdateAsync(CorporateClientOrderInfo objInfo, string token) {
            this.CorporateClientOrderEntryUpdateAsync(objInfo, token, null);
        }
        
        /// <remarks/>
        public void CorporateClientOrderEntryUpdateAsync(CorporateClientOrderInfo objInfo, string token, object userState) {
            if ((this.CorporateClientOrderEntryUpdateOperationCompleted == null)) {
                this.CorporateClientOrderEntryUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCorporateClientOrderEntryUpdateOperationCompleted);
            }
            this.InvokeAsync("CorporateClientOrderEntryUpdate", new object[] {
                        objInfo,
                        token}, this.CorporateClientOrderEntryUpdateOperationCompleted, userState);
        }
        
        private void OnCorporateClientOrderEntryUpdateOperationCompleted(object arg) {
            if ((this.CorporateClientOrderEntryUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CorporateClientOrderEntryUpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CorporateClientOrderEntryGetByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CorporateClientOrderInfo CorporateClientOrderEntryGetByID(int OrderID, string token) {
            object[] results = this.Invoke("CorporateClientOrderEntryGetByID", new object[] {
                        OrderID,
                        token});
            return ((CorporateClientOrderInfo)(results[0]));
        }
        
        /// <remarks/>
        public void CorporateClientOrderEntryGetByIDAsync(int OrderID, string token) {
            this.CorporateClientOrderEntryGetByIDAsync(OrderID, token, null);
        }
        
        /// <remarks/>
        public void CorporateClientOrderEntryGetByIDAsync(int OrderID, string token, object userState) {
            if ((this.CorporateClientOrderEntryGetByIDOperationCompleted == null)) {
                this.CorporateClientOrderEntryGetByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCorporateClientOrderEntryGetByIDOperationCompleted);
            }
            this.InvokeAsync("CorporateClientOrderEntryGetByID", new object[] {
                        OrderID,
                        token}, this.CorporateClientOrderEntryGetByIDOperationCompleted, userState);
        }
        
        private void OnCorporateClientOrderEntryGetByIDOperationCompleted(object arg) {
            if ((this.CorporateClientOrderEntryGetByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CorporateClientOrderEntryGetByIDCompleted(this, new CorporateClientOrderEntryGetByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchCorporateClientOrderEntry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SearchCorporateClientOrderEntry(string searchText, string token) {
            object[] results = this.Invoke("SearchCorporateClientOrderEntry", new object[] {
                        searchText,
                        token});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SearchCorporateClientOrderEntryAsync(string searchText, string token) {
            this.SearchCorporateClientOrderEntryAsync(searchText, token, null);
        }
        
        /// <remarks/>
        public void SearchCorporateClientOrderEntryAsync(string searchText, string token, object userState) {
            if ((this.SearchCorporateClientOrderEntryOperationCompleted == null)) {
                this.SearchCorporateClientOrderEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchCorporateClientOrderEntryOperationCompleted);
            }
            this.InvokeAsync("SearchCorporateClientOrderEntry", new object[] {
                        searchText,
                        token}, this.SearchCorporateClientOrderEntryOperationCompleted, userState);
        }
        
        private void OnSearchCorporateClientOrderEntryOperationCompleted(object arg) {
            if ((this.SearchCorporateClientOrderEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCorporateClientOrderEntryCompleted(this, new SearchCorporateClientOrderEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPageData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPageData(int current, int pagesize, string token) {
            object[] results = this.Invoke("GetPageData", new object[] {
                        current,
                        pagesize,
                        token});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPageDataAsync(int current, int pagesize, string token) {
            this.GetPageDataAsync(current, pagesize, token, null);
        }
        
        /// <remarks/>
        public void GetPageDataAsync(int current, int pagesize, string token, object userState) {
            if ((this.GetPageDataOperationCompleted == null)) {
                this.GetPageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPageDataOperationCompleted);
            }
            this.InvokeAsync("GetPageData", new object[] {
                        current,
                        pagesize,
                        token}, this.GetPageDataOperationCompleted, userState);
        }
        
        private void OnGetPageDataOperationCompleted(object arg) {
            if ((this.GetPageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPageDataCompleted(this, new GetPageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllCorporateClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CorporateClientInfo[] GetAllCorporateClient(string token) {
            object[] results = this.Invoke("GetAllCorporateClient", new object[] {
                        token});
            return ((CorporateClientInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCorporateClientAsync(string token) {
            this.GetAllCorporateClientAsync(token, null);
        }
        
        /// <remarks/>
        public void GetAllCorporateClientAsync(string token, object userState) {
            if ((this.GetAllCorporateClientOperationCompleted == null)) {
                this.GetAllCorporateClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCorporateClientOperationCompleted);
            }
            this.InvokeAsync("GetAllCorporateClient", new object[] {
                        token}, this.GetAllCorporateClientOperationCompleted, userState);
        }
        
        private void OnGetAllCorporateClientOperationCompleted(object arg) {
            if ((this.GetAllCorporateClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCorporateClientCompleted(this, new GetAllCorporateClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LocationNameGetByCorporateClientLocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CorporateClientLocationInfo[] LocationNameGetByCorporateClientLocation(int clientId, string token) {
            object[] results = this.Invoke("LocationNameGetByCorporateClientLocation", new object[] {
                        clientId,
                        token});
            return ((CorporateClientLocationInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void LocationNameGetByCorporateClientLocationAsync(int clientId, string token) {
            this.LocationNameGetByCorporateClientLocationAsync(clientId, token, null);
        }
        
        /// <remarks/>
        public void LocationNameGetByCorporateClientLocationAsync(int clientId, string token, object userState) {
            if ((this.LocationNameGetByCorporateClientLocationOperationCompleted == null)) {
                this.LocationNameGetByCorporateClientLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocationNameGetByCorporateClientLocationOperationCompleted);
            }
            this.InvokeAsync("LocationNameGetByCorporateClientLocation", new object[] {
                        clientId,
                        token}, this.LocationNameGetByCorporateClientLocationOperationCompleted, userState);
        }
        
        private void OnLocationNameGetByCorporateClientLocationOperationCompleted(object arg) {
            if ((this.LocationNameGetByCorporateClientLocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LocationNameGetByCorporateClientLocationCompleted(this, new LocationNameGetByCorporateClientLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CorporateClientOrderCancelByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CorporateClientOrderCancelByID(int OrderID, string token) {
            this.Invoke("CorporateClientOrderCancelByID", new object[] {
                        OrderID,
                        token});
        }
        
        /// <remarks/>
        public void CorporateClientOrderCancelByIDAsync(int OrderID, string token) {
            this.CorporateClientOrderCancelByIDAsync(OrderID, token, null);
        }
        
        /// <remarks/>
        public void CorporateClientOrderCancelByIDAsync(int OrderID, string token, object userState) {
            if ((this.CorporateClientOrderCancelByIDOperationCompleted == null)) {
                this.CorporateClientOrderCancelByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCorporateClientOrderCancelByIDOperationCompleted);
            }
            this.InvokeAsync("CorporateClientOrderCancelByID", new object[] {
                        OrderID,
                        token}, this.CorporateClientOrderCancelByIDOperationCompleted, userState);
        }
        
        private void OnCorporateClientOrderCancelByIDOperationCompleted(object arg) {
            if ((this.CorporateClientOrderCancelByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CorporateClientOrderCancelByIDCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CorporateClientOrderInfo {
        
        private int corporateClientOrderIDField;
        
        private int corporateClientIDField;
        
        private string clientNameField;
        
        private int contractIDField;
        
        private int fromIDField;
        
        private string courierNumberField;
        
        private string fromLocationField;
        
        private int toIDField;
        
        private string toLocationField;
        
        private string fromLocalAddressField;
        
        private string toLocalAddressField;
        
        private string fromContactPersonField;
        
        private string toContactPersonField;
        
        private string fromContactNumberField;
        
        private string toContactNumberField;
        
        private string packageNameField;
        
        private string serviceTypeNameField;
        
        private decimal chargeField;
        
        private int packageTypeIDField;
        
        private string packageTypeField;
        
        private string packageDescriptionField;
        
        private int numberOfPackageItemField;
        
        private decimal weightOfPackageField;
        
        private int weightUnitIDField;
        
        private string weightUnitField;
        
        private System.DateTime collectionDateField;
        
        private int paymentOptionIDField;
        
        private string contractDiscriptionField;
        
        private System.DateTime contractDateField;
        
        private System.DateTime contractExpireDateField;
        
        private string orderedByField;
        
        private System.DateTime orderedOnField;
        
        private string orderModifiedByField;
        
        private System.DateTime orderModifiedOnField;
        
        private bool isVerifiedField;
        
        private int statusField;
        
        private int rowTotalField;
        
        /// <remarks/>
        public int CorporateClientOrderID {
            get {
                return this.corporateClientOrderIDField;
            }
            set {
                this.corporateClientOrderIDField = value;
            }
        }
        
        /// <remarks/>
        public int CorporateClientID {
            get {
                return this.corporateClientIDField;
            }
            set {
                this.corporateClientIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public int ContractID {
            get {
                return this.contractIDField;
            }
            set {
                this.contractIDField = value;
            }
        }
        
        /// <remarks/>
        public int FromID {
            get {
                return this.fromIDField;
            }
            set {
                this.fromIDField = value;
            }
        }
        
        /// <remarks/>
        public string CourierNumber {
            get {
                return this.courierNumberField;
            }
            set {
                this.courierNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FromLocation {
            get {
                return this.fromLocationField;
            }
            set {
                this.fromLocationField = value;
            }
        }
        
        /// <remarks/>
        public int ToID {
            get {
                return this.toIDField;
            }
            set {
                this.toIDField = value;
            }
        }
        
        /// <remarks/>
        public string ToLocation {
            get {
                return this.toLocationField;
            }
            set {
                this.toLocationField = value;
            }
        }
        
        /// <remarks/>
        public string FromLocalAddress {
            get {
                return this.fromLocalAddressField;
            }
            set {
                this.fromLocalAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ToLocalAddress {
            get {
                return this.toLocalAddressField;
            }
            set {
                this.toLocalAddressField = value;
            }
        }
        
        /// <remarks/>
        public string FromContactPerson {
            get {
                return this.fromContactPersonField;
            }
            set {
                this.fromContactPersonField = value;
            }
        }
        
        /// <remarks/>
        public string ToContactPerson {
            get {
                return this.toContactPersonField;
            }
            set {
                this.toContactPersonField = value;
            }
        }
        
        /// <remarks/>
        public string FromContactNumber {
            get {
                return this.fromContactNumberField;
            }
            set {
                this.fromContactNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ToContactNumber {
            get {
                return this.toContactNumberField;
            }
            set {
                this.toContactNumberField = value;
            }
        }
        
        /// <remarks/>
        public string PackageName {
            get {
                return this.packageNameField;
            }
            set {
                this.packageNameField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceTypeName {
            get {
                return this.serviceTypeNameField;
            }
            set {
                this.serviceTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public decimal Charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        public int PackageTypeID {
            get {
                return this.packageTypeIDField;
            }
            set {
                this.packageTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string PackageType {
            get {
                return this.packageTypeField;
            }
            set {
                this.packageTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PackageDescription {
            get {
                return this.packageDescriptionField;
            }
            set {
                this.packageDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfPackageItem {
            get {
                return this.numberOfPackageItemField;
            }
            set {
                this.numberOfPackageItemField = value;
            }
        }
        
        /// <remarks/>
        public decimal WeightOfPackage {
            get {
                return this.weightOfPackageField;
            }
            set {
                this.weightOfPackageField = value;
            }
        }
        
        /// <remarks/>
        public int WeightUnitID {
            get {
                return this.weightUnitIDField;
            }
            set {
                this.weightUnitIDField = value;
            }
        }
        
        /// <remarks/>
        public string WeightUnit {
            get {
                return this.weightUnitField;
            }
            set {
                this.weightUnitField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CollectionDate {
            get {
                return this.collectionDateField;
            }
            set {
                this.collectionDateField = value;
            }
        }
        
        /// <remarks/>
        public int PaymentOptionID {
            get {
                return this.paymentOptionIDField;
            }
            set {
                this.paymentOptionIDField = value;
            }
        }
        
        /// <remarks/>
        public string ContractDiscription {
            get {
                return this.contractDiscriptionField;
            }
            set {
                this.contractDiscriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractDate {
            get {
                return this.contractDateField;
            }
            set {
                this.contractDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractExpireDate {
            get {
                return this.contractExpireDateField;
            }
            set {
                this.contractExpireDateField = value;
            }
        }
        
        /// <remarks/>
        public string OrderedBy {
            get {
                return this.orderedByField;
            }
            set {
                this.orderedByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderedOn {
            get {
                return this.orderedOnField;
            }
            set {
                this.orderedOnField = value;
            }
        }
        
        /// <remarks/>
        public string OrderModifiedBy {
            get {
                return this.orderModifiedByField;
            }
            set {
                this.orderModifiedByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderModifiedOn {
            get {
                return this.orderModifiedOnField;
            }
            set {
                this.orderModifiedOnField = value;
            }
        }
        
        /// <remarks/>
        public bool IsVerified {
            get {
                return this.isVerifiedField;
            }
            set {
                this.isVerifiedField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int RowTotal {
            get {
                return this.rowTotalField;
            }
            set {
                this.rowTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CorporateClientLocationInfo {
        
        private int corporateClientLocationIDField;
        
        private string fromLocationField;
        
        private int toLocationIDField;
        
        private int fromLocationIDField;
        
        private int locationIDField;
        
        private string locationNameField;
        
        private string toLocationField;
        
        private decimal chargeField;
        
        private int serviceTypeIDField;
        
        private string serviceTypeField;
        
        private int weightUnitIDField;
        
        private string contractDiscriptionField;
        
        private System.DateTime contractDateField;
        
        private System.DateTime contractExpireDateField;
        
        private string editedByField;
        
        private string addedByField;
        
        private System.DateTime addedDateField;
        
        private string deletedByField;
        
        private bool isDeletedField;
        
        private bool isModifiedField;
        
        private int corporateClientIDField;
        
        /// <remarks/>
        public int CorporateClientLocationID {
            get {
                return this.corporateClientLocationIDField;
            }
            set {
                this.corporateClientLocationIDField = value;
            }
        }
        
        /// <remarks/>
        public string FromLocation {
            get {
                return this.fromLocationField;
            }
            set {
                this.fromLocationField = value;
            }
        }
        
        /// <remarks/>
        public int ToLocationID {
            get {
                return this.toLocationIDField;
            }
            set {
                this.toLocationIDField = value;
            }
        }
        
        /// <remarks/>
        public int FromLocationID {
            get {
                return this.fromLocationIDField;
            }
            set {
                this.fromLocationIDField = value;
            }
        }
        
        /// <remarks/>
        public int LocationID {
            get {
                return this.locationIDField;
            }
            set {
                this.locationIDField = value;
            }
        }
        
        /// <remarks/>
        public string LocationName {
            get {
                return this.locationNameField;
            }
            set {
                this.locationNameField = value;
            }
        }
        
        /// <remarks/>
        public string ToLocation {
            get {
                return this.toLocationField;
            }
            set {
                this.toLocationField = value;
            }
        }
        
        /// <remarks/>
        public decimal Charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceTypeID {
            get {
                return this.serviceTypeIDField;
            }
            set {
                this.serviceTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        public int WeightUnitID {
            get {
                return this.weightUnitIDField;
            }
            set {
                this.weightUnitIDField = value;
            }
        }
        
        /// <remarks/>
        public string ContractDiscription {
            get {
                return this.contractDiscriptionField;
            }
            set {
                this.contractDiscriptionField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractDate {
            get {
                return this.contractDateField;
            }
            set {
                this.contractDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ContractExpireDate {
            get {
                return this.contractExpireDateField;
            }
            set {
                this.contractExpireDateField = value;
            }
        }
        
        /// <remarks/>
        public string EditedBy {
            get {
                return this.editedByField;
            }
            set {
                this.editedByField = value;
            }
        }
        
        /// <remarks/>
        public string AddedBy {
            get {
                return this.addedByField;
            }
            set {
                this.addedByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AddedDate {
            get {
                return this.addedDateField;
            }
            set {
                this.addedDateField = value;
            }
        }
        
        /// <remarks/>
        public string DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsModified {
            get {
                return this.isModifiedField;
            }
            set {
                this.isModifiedField = value;
            }
        }
        
        /// <remarks/>
        public int CorporateClientID {
            get {
                return this.corporateClientIDField;
            }
            set {
                this.corporateClientIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CorporateClientInfo {
        
        private int corporateClientIDField;
        
        private string clientNameField;
        
        private string addressField;
        
        private string phoneNumberField;
        
        private string emailAddressField;
        
        private string hOAddressField;
        
        private string lCDepartmentField;
        
        private string lCDContactPersonField;
        
        private string lCDContactPersonPhoneField;
        
        private string lCDContactPersonMobileField;
        
        private string lCDContactPersonEmailField;
        
        private string sLAField;
        
        private string addedByField;
        
        private System.DateTime addedDateField;
        
        private string editedByField;
        
        private string deletedByField;
        
        private bool isModifiedField;
        
        private bool isDeletedField;
        
        /// <remarks/>
        public int CorporateClientID {
            get {
                return this.corporateClientIDField;
            }
            set {
                this.corporateClientIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClientName {
            get {
                return this.clientNameField;
            }
            set {
                this.clientNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
            }
        }
        
        /// <remarks/>
        public string HOAddress {
            get {
                return this.hOAddressField;
            }
            set {
                this.hOAddressField = value;
            }
        }
        
        /// <remarks/>
        public string LCDepartment {
            get {
                return this.lCDepartmentField;
            }
            set {
                this.lCDepartmentField = value;
            }
        }
        
        /// <remarks/>
        public string LCDContactPerson {
            get {
                return this.lCDContactPersonField;
            }
            set {
                this.lCDContactPersonField = value;
            }
        }
        
        /// <remarks/>
        public string LCDContactPersonPhone {
            get {
                return this.lCDContactPersonPhoneField;
            }
            set {
                this.lCDContactPersonPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string LCDContactPersonMobile {
            get {
                return this.lCDContactPersonMobileField;
            }
            set {
                this.lCDContactPersonMobileField = value;
            }
        }
        
        /// <remarks/>
        public string LCDContactPersonEmail {
            get {
                return this.lCDContactPersonEmailField;
            }
            set {
                this.lCDContactPersonEmailField = value;
            }
        }
        
        /// <remarks/>
        public string SLA {
            get {
                return this.sLAField;
            }
            set {
                this.sLAField = value;
            }
        }
        
        /// <remarks/>
        public string AddedBy {
            get {
                return this.addedByField;
            }
            set {
                this.addedByField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AddedDate {
            get {
                return this.addedDateField;
            }
            set {
                this.addedDateField = value;
            }
        }
        
        /// <remarks/>
        public string EditedBy {
            get {
                return this.editedByField;
            }
            set {
                this.editedByField = value;
            }
        }
        
        /// <remarks/>
        public string DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        public bool IsModified {
            get {
                return this.isModifiedField;
            }
            set {
                this.isModifiedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CorporateClientOrderEntryAddCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CorporateClientOrderEntryUpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CorporateClientOrderEntryGetByIDCompletedEventHandler(object sender, CorporateClientOrderEntryGetByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CorporateClientOrderEntryGetByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CorporateClientOrderEntryGetByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CorporateClientOrderInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CorporateClientOrderInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SearchCorporateClientOrderEntryCompletedEventHandler(object sender, SearchCorporateClientOrderEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCorporateClientOrderEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCorporateClientOrderEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetPageDataCompletedEventHandler(object sender, GetPageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetAllCorporateClientCompletedEventHandler(object sender, GetAllCorporateClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCorporateClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCorporateClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CorporateClientInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CorporateClientInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void LocationNameGetByCorporateClientLocationCompletedEventHandler(object sender, LocationNameGetByCorporateClientLocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LocationNameGetByCorporateClientLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LocationNameGetByCorporateClientLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CorporateClientLocationInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CorporateClientLocationInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void CorporateClientOrderCancelByIDCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591