//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourierBackOfficeManagement.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/LoginWebService.asmx")]
        public string CourierBackOfficeManagement_Login_LoginWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_Login_LoginWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/CorporateClientWebService.asmx")]
        public string CourierBackOfficeManagement_CorporateClient_CorporateClientWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_CorporateClient_CorporateClientWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/LocationWebService.asmx")]
        public string CourierBackOfficeManagement_Location_LocationWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_Location_LocationWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/CountryWebService.asmx")]
        public string CourierBackOfficeManagement_Country_CountryWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_Country_CountryWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/GeneralCourierWebService.asmx")]
        public string CourierBackOfficeManagement_GeneralCourier_GeneralCourierWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_GeneralCourier_GeneralCourierWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/CorporateClientLocationWebService.asmx")]
        public string CourierBackOfficeManagement_CorporateClientLocation_CorporateClientLocationWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_CorporateClientLocation_CorporateClientLocationWebSer" +
                    "vice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/StateWebService.asmx")]
        public string CourierBackOfficeManagement_State_StateWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_State_StateWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/CorporateCourierEntryWebService.asmx")]
        public string CourierBackOfficeManagement_CorporateCourierEntry_CorporateCourierEntryWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_CorporateCourierEntry_CorporateCourierEntryWebService" +
                    ""]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/ExpenseHeadWebService.asmx")]
        public string CourierBackOfficeManagement_ExpenseHead_ExpenseHeadWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_ExpenseHead_ExpenseHeadWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/ExpenseWebService.asmx")]
        public string CourierBackOfficeManagement_Expense_ExpenseWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_Expense_ExpenseWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/GeneralCourierPriceWebService.asmx")]
        public string CourierBackOfficeManagement_GeneralCourierPrice_GeneralCourierPriceWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_GeneralCourierPrice_GeneralCourierPriceWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/CourierReportWebService.asmx")]
        public string CourierBackOfficeManagement_CourierReport_CourierReportWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_CourierReport_CourierReportWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44719/BackEndWebService/CompanyLogoAndAddressWebService.asmx")]
        public string CourierBackOfficeManagement_Logo_LogoWebService {
            get {
                return ((string)(this["CourierBackOfficeManagement_Logo_LogoWebService"]));
            }
        }
    }
}
