//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CourierBackOfficeManagement.Logo {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CompanyLogoAndAddressWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CompanyLogoAndAddressWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLogoPathOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompanyAddressOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CompanyLogoAndAddressWebService() {
            this.Url = global::CourierBackOfficeManagement.Properties.Settings.Default.CourierBackOfficeManagement_Logo_LogoWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLogoPathCompletedEventHandler GetLogoPathCompleted;
        
        /// <remarks/>
        public event GetCompanyAddressCompletedEventHandler GetCompanyAddressCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLogoPath", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLogoPath(int userModuleID, int portalID, string CultureCode, string UserName, string secureToken) {
            object[] results = this.Invoke("GetLogoPath", new object[] {
                        userModuleID,
                        portalID,
                        CultureCode,
                        UserName,
                        secureToken});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLogoPathAsync(int userModuleID, int portalID, string CultureCode, string UserName, string secureToken) {
            this.GetLogoPathAsync(userModuleID, portalID, CultureCode, UserName, secureToken, null);
        }
        
        /// <remarks/>
        public void GetLogoPathAsync(int userModuleID, int portalID, string CultureCode, string UserName, string secureToken, object userState) {
            if ((this.GetLogoPathOperationCompleted == null)) {
                this.GetLogoPathOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLogoPathOperationCompleted);
            }
            this.InvokeAsync("GetLogoPath", new object[] {
                        userModuleID,
                        portalID,
                        CultureCode,
                        UserName,
                        secureToken}, this.GetLogoPathOperationCompleted, userState);
        }
        
        private void OnGetLogoPathOperationCompleted(object arg) {
            if ((this.GetLogoPathCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLogoPathCompleted(this, new GetLogoPathCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCompanyAddress", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetCompanyAddress(int userModuleID, int portalID, string CultureCode) {
            object[] results = this.Invoke("GetCompanyAddress", new object[] {
                        userModuleID,
                        portalID,
                        CultureCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompanyAddressAsync(int userModuleID, int portalID, string CultureCode) {
            this.GetCompanyAddressAsync(userModuleID, portalID, CultureCode, null);
        }
        
        /// <remarks/>
        public void GetCompanyAddressAsync(int userModuleID, int portalID, string CultureCode, object userState) {
            if ((this.GetCompanyAddressOperationCompleted == null)) {
                this.GetCompanyAddressOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompanyAddressOperationCompleted);
            }
            this.InvokeAsync("GetCompanyAddress", new object[] {
                        userModuleID,
                        portalID,
                        CultureCode}, this.GetCompanyAddressOperationCompleted, userState);
        }
        
        private void OnGetCompanyAddressOperationCompleted(object arg) {
            if ((this.GetCompanyAddressCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompanyAddressCompleted(this, new GetCompanyAddressCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetLogoPathCompletedEventHandler(object sender, GetLogoPathCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLogoPathCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLogoPathCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetCompanyAddressCompletedEventHandler(object sender, GetCompanyAddressCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompanyAddressCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompanyAddressCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591