//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CourierBackOfficeManagement.GeneralCourier {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GeneralCourierWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class GeneralCourierWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GeneralCourierAddOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneralCourierUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneralCourierGetAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneralCourierGetByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneralCourierDeleteByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchCourierOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPageDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GeneralCourierWebService() {
            this.Url = global::CourierBackOfficeManagement.Properties.Settings.Default.CourierBackOfficeManagement_GeneralCourier_GeneralCourierWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GeneralCourierAddCompletedEventHandler GeneralCourierAddCompleted;
        
        /// <remarks/>
        public event GeneralCourierUpdateCompletedEventHandler GeneralCourierUpdateCompleted;
        
        /// <remarks/>
        public event GeneralCourierGetAllCompletedEventHandler GeneralCourierGetAllCompleted;
        
        /// <remarks/>
        public event GeneralCourierGetByIDCompletedEventHandler GeneralCourierGetByIDCompleted;
        
        /// <remarks/>
        public event GeneralCourierDeleteByIDCompletedEventHandler GeneralCourierDeleteByIDCompleted;
        
        /// <remarks/>
        public event SearchCourierCompletedEventHandler SearchCourierCompleted;
        
        /// <remarks/>
        public event GetPageDataCompletedEventHandler GetPageDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneralCourierAdd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GeneralCourierAdd(GeneralCourierInfo objInfo, string token) {
            this.Invoke("GeneralCourierAdd", new object[] {
                        objInfo,
                        token});
        }
        
        /// <remarks/>
        public void GeneralCourierAddAsync(GeneralCourierInfo objInfo, string token) {
            this.GeneralCourierAddAsync(objInfo, token, null);
        }
        
        /// <remarks/>
        public void GeneralCourierAddAsync(GeneralCourierInfo objInfo, string token, object userState) {
            if ((this.GeneralCourierAddOperationCompleted == null)) {
                this.GeneralCourierAddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneralCourierAddOperationCompleted);
            }
            this.InvokeAsync("GeneralCourierAdd", new object[] {
                        objInfo,
                        token}, this.GeneralCourierAddOperationCompleted, userState);
        }
        
        private void OnGeneralCourierAddOperationCompleted(object arg) {
            if ((this.GeneralCourierAddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneralCourierAddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneralCourierUpdate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GeneralCourierUpdate(GeneralCourierInfo objInfo, string token) {
            this.Invoke("GeneralCourierUpdate", new object[] {
                        objInfo,
                        token});
        }
        
        /// <remarks/>
        public void GeneralCourierUpdateAsync(GeneralCourierInfo objInfo, string token) {
            this.GeneralCourierUpdateAsync(objInfo, token, null);
        }
        
        /// <remarks/>
        public void GeneralCourierUpdateAsync(GeneralCourierInfo objInfo, string token, object userState) {
            if ((this.GeneralCourierUpdateOperationCompleted == null)) {
                this.GeneralCourierUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneralCourierUpdateOperationCompleted);
            }
            this.InvokeAsync("GeneralCourierUpdate", new object[] {
                        objInfo,
                        token}, this.GeneralCourierUpdateOperationCompleted, userState);
        }
        
        private void OnGeneralCourierUpdateOperationCompleted(object arg) {
            if ((this.GeneralCourierUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneralCourierUpdateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneralCourierGetAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GeneralCourierInfo[] GeneralCourierGetAll(string token) {
            object[] results = this.Invoke("GeneralCourierGetAll", new object[] {
                        token});
            return ((GeneralCourierInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GeneralCourierGetAllAsync(string token) {
            this.GeneralCourierGetAllAsync(token, null);
        }
        
        /// <remarks/>
        public void GeneralCourierGetAllAsync(string token, object userState) {
            if ((this.GeneralCourierGetAllOperationCompleted == null)) {
                this.GeneralCourierGetAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneralCourierGetAllOperationCompleted);
            }
            this.InvokeAsync("GeneralCourierGetAll", new object[] {
                        token}, this.GeneralCourierGetAllOperationCompleted, userState);
        }
        
        private void OnGeneralCourierGetAllOperationCompleted(object arg) {
            if ((this.GeneralCourierGetAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneralCourierGetAllCompleted(this, new GeneralCourierGetAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneralCourierGetByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GeneralCourierInfo GeneralCourierGetByID(int GeneralCourierID, string token) {
            object[] results = this.Invoke("GeneralCourierGetByID", new object[] {
                        GeneralCourierID,
                        token});
            return ((GeneralCourierInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GeneralCourierGetByIDAsync(int GeneralCourierID, string token) {
            this.GeneralCourierGetByIDAsync(GeneralCourierID, token, null);
        }
        
        /// <remarks/>
        public void GeneralCourierGetByIDAsync(int GeneralCourierID, string token, object userState) {
            if ((this.GeneralCourierGetByIDOperationCompleted == null)) {
                this.GeneralCourierGetByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneralCourierGetByIDOperationCompleted);
            }
            this.InvokeAsync("GeneralCourierGetByID", new object[] {
                        GeneralCourierID,
                        token}, this.GeneralCourierGetByIDOperationCompleted, userState);
        }
        
        private void OnGeneralCourierGetByIDOperationCompleted(object arg) {
            if ((this.GeneralCourierGetByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneralCourierGetByIDCompleted(this, new GeneralCourierGetByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneralCourierDeleteByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GeneralCourierDeleteByID(int GeneralCourierID, string token) {
            this.Invoke("GeneralCourierDeleteByID", new object[] {
                        GeneralCourierID,
                        token});
        }
        
        /// <remarks/>
        public void GeneralCourierDeleteByIDAsync(int GeneralCourierID, string token) {
            this.GeneralCourierDeleteByIDAsync(GeneralCourierID, token, null);
        }
        
        /// <remarks/>
        public void GeneralCourierDeleteByIDAsync(int GeneralCourierID, string token, object userState) {
            if ((this.GeneralCourierDeleteByIDOperationCompleted == null)) {
                this.GeneralCourierDeleteByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneralCourierDeleteByIDOperationCompleted);
            }
            this.InvokeAsync("GeneralCourierDeleteByID", new object[] {
                        GeneralCourierID,
                        token}, this.GeneralCourierDeleteByIDOperationCompleted, userState);
        }
        
        private void OnGeneralCourierDeleteByIDOperationCompleted(object arg) {
            if ((this.GeneralCourierDeleteByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneralCourierDeleteByIDCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchCourier", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SearchCourier(string searchText, string token) {
            object[] results = this.Invoke("SearchCourier", new object[] {
                        searchText,
                        token});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SearchCourierAsync(string searchText, string token) {
            this.SearchCourierAsync(searchText, token, null);
        }
        
        /// <remarks/>
        public void SearchCourierAsync(string searchText, string token, object userState) {
            if ((this.SearchCourierOperationCompleted == null)) {
                this.SearchCourierOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchCourierOperationCompleted);
            }
            this.InvokeAsync("SearchCourier", new object[] {
                        searchText,
                        token}, this.SearchCourierOperationCompleted, userState);
        }
        
        private void OnSearchCourierOperationCompleted(object arg) {
            if ((this.SearchCourierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchCourierCompleted(this, new SearchCourierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPageData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPageData(int current, int pagesize, string token) {
            object[] results = this.Invoke("GetPageData", new object[] {
                        current,
                        pagesize,
                        token});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPageDataAsync(int current, int pagesize, string token) {
            this.GetPageDataAsync(current, pagesize, token, null);
        }
        
        /// <remarks/>
        public void GetPageDataAsync(int current, int pagesize, string token, object userState) {
            if ((this.GetPageDataOperationCompleted == null)) {
                this.GetPageDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPageDataOperationCompleted);
            }
            this.InvokeAsync("GetPageData", new object[] {
                        current,
                        pagesize,
                        token}, this.GetPageDataOperationCompleted, userState);
        }
        
        private void OnGetPageDataOperationCompleted(object arg) {
            if ((this.GetPageDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPageDataCompleted(this, new GetPageDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GeneralCourierInfo {
        
        private int generalCourierIDField;
        
        private string courierNumberField;
        
        private string receiverFullNameField;
        
        private string senderFullNameField;
        
        private string receiverFirstNameField;
        
        private string receiverMiddleNameField;
        
        private string receiverLastNameField;
        
        private string receiverAddressField;
        
        private int receiverMobileField;
        
        private int receiverPhoneField;
        
        private int numberOfPackageField;
        
        private decimal weightOfPackageField;
        
        private string packageWeightField;
        
        private string serviceTypeField;
        
        private int serviceTypeIDField;
        
        private int weightUnitIDField;
        
        private string senderFirstNameField;
        
        private string senderMiddleNameField;
        
        private string senderLastNameField;
        
        private string senderAddressField;
        
        private int senderMobileField;
        
        private int senderPhoneField;
        
        private string addedByField;
        
        private string updatedByField;
        
        private string deletedByField;
        
        private bool isDeletedField;
        
        private System.DateTime addedOnField;
        
        private System.DateTime updatedOnField;
        
        private System.DateTime deletedOnField;
        
        /// <remarks/>
        public int GeneralCourierID {
            get {
                return this.generalCourierIDField;
            }
            set {
                this.generalCourierIDField = value;
            }
        }
        
        /// <remarks/>
        public string CourierNumber {
            get {
                return this.courierNumberField;
            }
            set {
                this.courierNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverFullName {
            get {
                return this.receiverFullNameField;
            }
            set {
                this.receiverFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string SenderFullName {
            get {
                return this.senderFullNameField;
            }
            set {
                this.senderFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverFirstName {
            get {
                return this.receiverFirstNameField;
            }
            set {
                this.receiverFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverMiddleName {
            get {
                return this.receiverMiddleNameField;
            }
            set {
                this.receiverMiddleNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverLastName {
            get {
                return this.receiverLastNameField;
            }
            set {
                this.receiverLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverAddress {
            get {
                return this.receiverAddressField;
            }
            set {
                this.receiverAddressField = value;
            }
        }
        
        /// <remarks/>
        public int ReceiverMobile {
            get {
                return this.receiverMobileField;
            }
            set {
                this.receiverMobileField = value;
            }
        }
        
        /// <remarks/>
        public int ReceiverPhone {
            get {
                return this.receiverPhoneField;
            }
            set {
                this.receiverPhoneField = value;
            }
        }
        
        /// <remarks/>
        public int NumberOfPackage {
            get {
                return this.numberOfPackageField;
            }
            set {
                this.numberOfPackageField = value;
            }
        }
        
        /// <remarks/>
        public decimal WeightOfPackage {
            get {
                return this.weightOfPackageField;
            }
            set {
                this.weightOfPackageField = value;
            }
        }
        
        /// <remarks/>
        public string PackageWeight {
            get {
                return this.packageWeightField;
            }
            set {
                this.packageWeightField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceTypeID {
            get {
                return this.serviceTypeIDField;
            }
            set {
                this.serviceTypeIDField = value;
            }
        }
        
        /// <remarks/>
        public int WeightUnitID {
            get {
                return this.weightUnitIDField;
            }
            set {
                this.weightUnitIDField = value;
            }
        }
        
        /// <remarks/>
        public string SenderFirstName {
            get {
                return this.senderFirstNameField;
            }
            set {
                this.senderFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string SenderMiddleName {
            get {
                return this.senderMiddleNameField;
            }
            set {
                this.senderMiddleNameField = value;
            }
        }
        
        /// <remarks/>
        public string SenderLastName {
            get {
                return this.senderLastNameField;
            }
            set {
                this.senderLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string SenderAddress {
            get {
                return this.senderAddressField;
            }
            set {
                this.senderAddressField = value;
            }
        }
        
        /// <remarks/>
        public int SenderMobile {
            get {
                return this.senderMobileField;
            }
            set {
                this.senderMobileField = value;
            }
        }
        
        /// <remarks/>
        public int SenderPhone {
            get {
                return this.senderPhoneField;
            }
            set {
                this.senderPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string AddedBy {
            get {
                return this.addedByField;
            }
            set {
                this.addedByField = value;
            }
        }
        
        /// <remarks/>
        public string UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
            }
        }
        
        /// <remarks/>
        public string DeletedBy {
            get {
                return this.deletedByField;
            }
            set {
                this.deletedByField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                this.isDeletedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AddedOn {
            get {
                return this.addedOnField;
            }
            set {
                this.addedOnField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdatedOn {
            get {
                return this.updatedOnField;
            }
            set {
                this.updatedOnField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DeletedOn {
            get {
                return this.deletedOnField;
            }
            set {
                this.deletedOnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GeneralCourierAddCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GeneralCourierUpdateCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GeneralCourierGetAllCompletedEventHandler(object sender, GeneralCourierGetAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneralCourierGetAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneralCourierGetAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralCourierInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralCourierInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GeneralCourierGetByIDCompletedEventHandler(object sender, GeneralCourierGetByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneralCourierGetByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneralCourierGetByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GeneralCourierInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GeneralCourierInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GeneralCourierDeleteByIDCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void SearchCourierCompletedEventHandler(object sender, SearchCourierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchCourierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchCourierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetPageDataCompletedEventHandler(object sender, GetPageDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPageDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPageDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591